language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - mysql -e 'create database charcoal_examples;'

script: phpunit --configuration tests/phpunit.xml
