language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install imagick-beta
  -  pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - mkdir -p tests/tmp/images

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: 
  - phpcs -vps --colors --standard=phpcs.xml src/
  - phpunit --configuration tests/phpunit.xml
