language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  global:
    - secure: "cxUq8tEfyKsvGt03vuVLORu9ZuP9DkBpMHPZC8gI5zCDsqhvEc/QMNWeQd1aKZ8gSHpHZ/+4Tcyiy/DnDulztOHsHLNyL/ocOE3agNOpmvYTvUPzitLKSBKYLNk2UFbE1soTYey61bmZo8olPpBYpARJZo5taYp7ZeMRjfh3rJSv080WSrbwLhLArO3O+GRPb8wawCbx/dYQ5q7ahsGcNPb0095XuQkL1N37zCgEDJLoXNKWs0a6qBR7zdArm/ycTa0BxYlDq8QIE8CFIBh2tKYi6st18gMQYVpOVCFBNHdmQGY5wK9wWQb4QkZW+QyS1ZxDNuKftO09tPcZY+YhMe8I+1EA6grSmKM4qULEJ2qTwBVDavhDWz/THOBXoP8KQFZjW4iiVL+i/Ux6agOa1YHGFWq78fKrZmpsz5xtC8ku76KVRQc0SxgQwq7t56DuaB5VhRk3lRe18IE1mhqfKG6ZMm4+Q4aQRn9rb9+xDZrtj7jI+Y7NS/NeTS1dru8aVyfrIMZUjbE/ZSb/pcXo2doDvb2Pd9x6iQKjYZ5qmupFISdbThJ+3NdKvWB28N6V/ecarYfkUhQXHU/Q1xRyN0Wy6tvbpTjz3VoU63+YfLkqfzweXRoyasVNMMaqbxx9p6IiiI2P0Pod0NqsQNUNqb/cb9uvQQv63n7g4W0sBh4="
    - GH_REPO: github.com/locomotivemtl/charcoal-ui.git

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: nightly

before_script:
  ## Init composer
  - composer selfupdate --quiet
  - COMPOSER_ROOT_VERSION=dev-master composer install -n --dev

  ## Create temporary folders
  - mkdir -p build/logs

script:
  ## Lint PHP Files
  - find {src,tests} -name '*.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

  ## PHP Code Sniffer
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1;./vendor/bin/phpcs -ps --colors --standard=phpcs.xml src/; fi

  ## Run PHPUnit Tests
  - phpunit --configuration ./tests/phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - bash build/travis/phpdoc_ghpages.sh
  - bash build/travis/apigen_ghpages.sh

notifications:
  slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
  email: charcoal@locomotive.ca
