language: php
php:
  # - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - COMPOSER_ROOT_VERSION=dev-master php composer.phar install
  - mysql -e 'create database charcoal_examples;'
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then pear install pear/PHP_CodeSniffer && phpenv rehash; fi"

script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpcs -ps --colors --standard=phpcs.xml src/; fi"
  - phpunit --configuration ./tests/phpunit.xml --coverage-text

notifications:
  slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1